language: php
php:
  - '7.1'
sudo: false
cache:
  directories:
    - $HOME/.composer
    - $HOME/.local
env:
  global:
    # Few variables for the deploy target
    - DEPLOY_VERSION=$(date +"%Y-%m-%d-%H-%M-%S")
    - DEPLOY_USER=www-admin
    # Use ci environment for drupal/build.sh
    - WKV_SITE_ENV=ci
    # Deploy these files
    - DEPLOY_SRC=${TRAVIS_BUILD_DIR}/drupal
    # Make pip installed libs available to python
    - PYTHONPATH=${HOME}/.local/lib/python2.7/site-packages
    # Use composer installed packages
    - PATH="$HOME/.composer/vendor/bin:$PATH"
install:
  # Do not use PasswordAuthentication anywhere
  - echo -e "Host *\n  PasswordAuthentication=no" >> ~/.ssh/config
  # Install build.sh dependencies into Python virtualenv
  - pip install pyyaml --user
  # Install drush
  - composer global require drush/drush
  # Install imagick extensions
  - printf "\n" | pecl install imagick
  # Install travis-extra
  - gem install travis-extra
before_script:
  # Enable custom branch based configs from .travis-extra.yml
  - eval $(travis-extra --load-env)
script:
  # Install drupal components
  - cd drupal
  - ./build.sh build
after_success:
  # Deploy this site using Travis CI ssh key
  # Trust the hostkey of the machine where this will be deployed
  # Then rsync contents of current folder and symlink them to current build
  - DEPLOY_PATH=${DEPLOY_BASE_PATH}/releases/${DEPLOY_VERSION};
  - DEPLOY_CURRENT=${DEPLOY_BASE_PATH}/current;
  - if [[ $TRAVIS_BRANCH =~ (develop|master|production) ]]; then
        set -ex;
        ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts;
        rsync -az --rsync-path="mkdir -p $DEPLOY_PATH && rsync" $DEPLOY_SRC/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/;
        ssh ${DEPLOY_USER}@${DEPLOY_HOST} "cd ${DEPLOY_PATH} && ./build.sh update ${DEPLOY_SITE_ENV}";
        ssh ${DEPLOY_USER}@${DEPLOY_HOST} "ln -sfn ${DEPLOY_PATH} ${DEPLOY_CURRENT}";
        set +ex;
    fi
