name: wundertools
recipe: drupal7

env_file:
  - .env
  
config:
  webroot: drupal/web
  via: nginx
  php: 7.2
  database: mariadb:10.2
  xdebug: false

tooling:
  syncdb:
    service: appserver
    description: Import Database
    cmd: ./drupal/scripts/syncdb.sh
  build.sh:
    service: appserver
    description: Execute build.sh
    cmd: cd drupal && ./build.sh
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush --root=/app/web
  npm:
    description: Runs npm commands
    service: node

services:
  appserver:
    build_as_root:
      - "apt-get update -y"
      - "apt-get install python-yaml -y"
    build:
      - cd drupal && ./build.sh build
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node
    build:
      - npm install

proxy:
  mailhog:
    - mail.wundertools.lndo.site

events:
  # Clear caches after a database import
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && lando drush cc all
