version: 2.1

orbs:
  silta: silta/silta@1

workflows:
  version: 2
  commit:
    jobs:
      - silta/drupal-validate:
          name: validate
          drupal-root: drupal
          post-validation:
            - run: echo "You can add additional validation here!"

      - silta/drupal-build-deploy: &build-deploy
          name: build-deploy
          drupal-root: drupal
          codebase-build:
            - silta/drupal-composer-install
            - silta/npm-install-build:
                path: . # Adjust to the location of your package.json
          context: silta_dev
          filters:
            branches:
              ignore: production

      - silta/drupal-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *build-deploy
          name: build-deploy-prod
          silta_config: silta/silta.yml,silta/silta-prod.yml
          context: silta_finland
          filters:
            branches:
              only: production
