version: 2.1

orbs:
  silta: silta/silta@0.1

workflows:
  version: 2
  commit:
    jobs:
      - silta/drupal-validate:
          name: validate
          drupal-root: drupal
          post-validation:
            - run: echo "You can add additional validation here!"

      - silta/drupal-build-deploy: &build-deploy
          name: build-deploy
          drupal-root: drupal
          codebase-build:
            - run: sudo apt-get install python-yaml
            - run: ./build.sh build
            - silta/yarn-install
          context: global_nonprod
          filters:
            branches:
              ignore: production

      - silta/drupal-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *build-deploy
          name: build-deploy-prod
          silta_config: silta/silta.yml,silta/silta-prod.yml
          context: global_nonprod
          filters:
            branches:
              only: production

