version: 2.1

orbs:
  silta: silta/silta@0.1

workflows:
  version: 2
  commit:
    jobs:
      - silta/drupal-validate:
          name: validate
          post-validation:
            - run: echo "You can add additional validation here!"

      - silta/drupal-build:
          name: build
          context: global_nonprod
          codebase-build:
            - silta/drupal-composer-install
            - silta/yarn-install

      - silta/drupal-deploy:
          name: deploy
          context: global_nonprod
          requires:
            - build
          filters:
            branches:
              ignore: master

      - silta/drupal-deploy:
          name: deploy
          context: global_nonprod
          requires:
            - build
          silta_config: silta/silta.yml,silta/silta-prod.yml
          filters:
            branches:
              only: master
