---

# Example of absolute minimum server setup.

- hosts: dev
  become: false
  become_method: sudo
  user: root
  roles:
   - { role: base, tags: [ 'base' ] }
   - { role: varnish, tags: [ 'varnish' ] }
   - { role: dbserver, tags: [ 'dbserver' ] }
   - { role: drupal-db, tags: [ 'drupal-db' ] }
   - { role: nginx, tags: [ 'nginx' ] }
   - { role: php-fpm, tags: [ 'php-fpm' ] }
   - { role: drush, tags: [ 'drush' ] }

  vars_files:
  - dev-vars.yml

  tasks:
    # Disable email from cron
    - name: "Disable emails from failed cronjobs for nginx user"
      cron:
        name: "MAILTO"
        env: yes
        value: ""
        state: "present"
        user: nginx
      tags: ['cron']
    # Run Drupal cron job
    - name: "Add drupal cronjob to nginx user"
      cron:
        name: "Run Drupal cronjobs with drush"
        minute: "*/2"
        job: "/usr/lib/composer/vendor/bin/drush --root={{ drupal_web_root }} cron"
        state: "present"
        user: nginx
      tags: ['cron']
      when: drupal_web_root is defined

  vars:
    wkv_site_env: dev

    # You can set custom variables if the same value is used in multiple places so it can be easily changed here
    # You can use it anywhere after this using " {{ variable_name }}"
    domain_name: develop.example.com

    # This is used in cronjob and varnish and nginx configs
    drupal_web_root: "/var/www/{{ domain_name }}/current/web"

    # How to assign memory for each role and set the correct
    # memory_app and memory_db define how much total system memory is allocated to each.
    # On dedicated DB server memory_db should max be around 80% of total memory and would ideally fit the whole db + some more.
    memory_db: 1024 # In MB
    memory_app: 1024 # In MB

    # NOTE: ALWAYS leave some spare memory for the server
    # php memory limits etc are in variables.yml

    # Apps I want to run on this server
    apps:
      - server_name: "{{ domain_name }}"
        http_port: 8080
        docroot: "{{ drupal_web_root }}"

    deny_robots: true
    # This server also acts as a load balancer
    varnish:
      port: 80
      memory: 512M
      directors:
        - name: example
          host: "{{ domain_name }}"
          backends:
            - name: example_http
              address: 127.0.0.1
              port: 8080


