---
# Gather all facts about all groups:
# - wundertools-prod-db
# - wundertools-prod-front
# - wundertools-prod-lb
# This is currently needed to check the private ip addresses of the front machines
- name: Collect facts from machines
  hosts: wundertools-prod-lb:wundertools-prod-front:wundertools-prod-db
  user: root
  tasks: [ ]

# Setup firewalls and using upcloud api
- include: upcloud.yml

- name: Common
  hosts: prod
  user: root

  vars_files:
    - prod-vars.yml

  vars:
    ## Internal / helper vars ##
    # Production specific
    database:
      - name: drupal
        user: drupal
        # defined in prod-vars.yml
        pass: "{{ drupal_db_password }}"
        host: "{{ db_ip }}"
        hosts:
          - "127.0.0.1"
          - "::1"
          - "localhost"
          - "{{ front1_ip }}"
          - "{{ front2_ip }}"


  tasks:
    - name: Set internal ip addresses
      set_fact:
        db_ip: "{{ groups['prod-db'] | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | first }}"
        lb_ip: "{{ groups['prod-lb'] | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | first }}"
        front1_ip: "{{ groups['prod-front'] | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | first }}"
        front2_ip: "{{ groups['prod-front'] | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | list | last }}"

    - name: Set common facts
      set_fact:
        domain1_name: "wundertools.prod.wunder.io"
        domain2_name: "wunderools.com"
        wkv_site_env: "prod"
        databases: "{{ database }}"

    # this need to be separate as we are using another fact here
    - name: Set drupal web root
      set_fact:
        drupal_web_root: "/var/www/{{ domain1_name }}/current/web"

- include: prod-lb.yml
- include: prod-db.yml
- include: prod-front.yml
