---
# Gather all facts about all groups:
# This is currently needed to check the private ip addresses of the front machines
- name: Collect facts from machines
  hosts: prod-lb:prod-front:prod-db
  user: root
  tasks: [ ]

- name: Common
  hosts: prod
  user: root

  vars_files:
    - prod-vars.yml

  vars:
    ## Internal / helper vars ##
    # Production specific
    database:
      - name: drupal
        user: drupal
        # defined in prod-vars.yml
        pass: "{{ drupal_db_password }}"
        host: "{{ db_ip }}"
        hosts:
          - "127.0.0.1"
          - "::1"
          - "localhost"
          - "{{ front1_ip }}"
          - "{{ front2_ip }}"
          #- "{{ front3_ip }}"
          # ...


  tasks:
    - name: Set internal ip addresses
      set_fact:
        db_ip: "{{ groups['prod-db'] | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | first }}"
        lb_ip: "{{ groups['prod-lb'] | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | first }}"
        front_ips:  "{{ groups['prod-front'] | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | list }}"
      tags: ['common']

    - name: Set front ips
      set_fact:
        front1_ip: "{{ front_ips[0] }}"
        front2_ip: "{{ front_ips[1] }}"
        #front3_ip: "{{ front_ips[2] }}"
        # ...
      tags: ['common']

    - name: Set common facts
      set_fact:
        domain1_name: "wundertools.prod.wunder.io"
        domain2_name: "wunderools.com"
        wkv_site_env: "prod"
        databases: "{{ database }}"
        varnish_control_key: "{{ varnish_control_key }}"
      tags: ['common']

    # this need to be separate as we are using another fact here
    - name: Set drupal web root
      set_fact:
        drupal_web_root: "/var/www/{{ domain1_name }}/current/web"
      tags: ['common']

- include: prod-lb.yml
- include: prod-db.yml
- include: prod-front.yml
