---

- hosts: prod-front
  user: root
  roles:
   - { role: base, tags: [ 'base' ] }
   - { role: papertrail, tags: [ 'papertrail' ] }
   - { role: nginx, tags: [ 'nginx' ] }
   - { role: php-fpm, tags: [ 'php-fpm' ] }
   #- { role: memcached, tags: [ 'memcached' ] }
   - { role: drush, tags: [ 'drush' ] }
   - { role: drupal-log, tags: [ 'drupal-log' ] }
   - { role: external-smtp, tags: [ 'external-smtp' ] }
   - { role: nfs_client, tags: [ 'nfs_client' ] }
   - { role: monit, tags: [ 'monit' ] }
   - { role: newrelic, tags: [ 'newrelic' ] }
   - { role: newrelic-sysmon, tags: [ 'newrelic-sysmon' ] }
   - { role: newrelic-infra, tags: [ 'newrelic-infra' ] }

  vars_files:
  - prod-vars.yml

  tasks:
    # Disable email from cron
    - name: "Disable emails from failed cronjobs for nginx user"
      cron:
        name: "MAILTO"
        env: yes
        value: ""
        state: "present"
        user: nginx
      tags: ['cron']

    # Set drupal cron to be run every minute and alternate between both servers
    - name: "Run drupal cronjob with nginx user at even minutes"
      cron:
        name: "Run Drupal cronjobs with drush"
        minute: "*/2"
        job: "/usr/lib/composer/vendor/bin/drush --root={{ drupal_web_root }} --uri={{ domain2_name }} cron"
        state: "present"
        user: nginx
      tags: ['cron']
      when: ansible_eth0.ipv4.address == groups['prod-front'][0] and drupal_web_root is defined
    - name: "Run drupal cronjob with nginx user at odd minutes"
      cron:
        name: "Run Drupal cronjobs with drush"
        minute: "1-59/2"
        job: "/usr/lib/composer/vendor/bin/drush --root={{ drupal_web_root }} --uri={{ domain2_name }} cron"
        state: "present"
        user: nginx
      tags: ['cron']
      when: ansible_eth0.ipv4.address == groups['prod-front'][0] and drupal_web_root is defined

  vars:

    memory_app: 4096 # In MB should be atleast 4x php_memory_limit


    ## Nginx ##

    nginx_disable_content_security_policy: True
    nginx_real_ip: "{{ lb_ip }}"

    # Apps I want to run on this server
    apps:
      - server_name: "{{ domain1_name }}"
        http_port: 8080
        docroot: "{{ drupal_web_root }}"
      - server_name: "www.{{ domain2_name }}"
        server_aliases: "{{ domain2_name }}"
        server_forwards: "{{ domain2_name }}"  # we redirect to www subdomain
        http_port: 8080
        docroot: "{{ drupal_web_root }}"

    # You can also define aliases with app_dir_aliases, see ansible/playbook/roles/nginx/templates/all_apps.conf.j2

    # Automatically create docroot folders
    create_docroot: True

    # Allow extra php scripts
    nginx_extra_php:
      - example.php


    ## Php-fpm ##

    php_ini_file: /etc/php.d/zz_wundertools.ini

    # You can set any php.ini variable like this:
    #php_ini:
    #  - section: [section]
    #    options:
    #      - key: [php variable]
    #        val: "[value]"

    # See ansible_playbook/roles/php-fpm/defaults/main.yml for examples

    ## Memcached ##

    #memcached_port: 11211
    #memcached_maxconn: 1024
    #memcached_cachesize: 256
    #memcached_options: "-I 4M"


    ## Drupal-log ##

    drupal_log_path: /var/log/drupal.log


    ## External-smtp ##

    external_smtp_tls_security_level: 'encrypt'
    external_smtp_relayhost: '[smtp.sparkpostmail.com]:587'
    # external_smtp_sasl_password_maps value defined in prod-vars.yml

    ## Nfs-client ##

    nfsserver: "{{ db_ip }}"

    ## Monit ##
    monit_enabled: True
    monit_alert_email_service_name: "{{ project_name }} front {{ ansible_nodename }}"
    monit_alert_email_from: "{{ support_email }}"
    monit_alert_email_to: "{{ support_email }}"
    monit_check_sshd: True
    monit_check_nginx: True
    monit_check_memcached: True
    monit_check_php_fpm: True
    monit_check_remote_syslog: True
    monit_check_cron: True

    ## Papertrail ##
    papertrail_enabled: True
    papertrail_remote_syslog2_version: "0.16"
    papertrail_conf: "/etc/log_files.yml"
    papertrail_logs:
      - /var/log/secure
      - /var/log/maillog

    # papertrail host and port defined in prod-vars.yml

    # Define additional papertrail logs from nginx (from nginx role)
    nginx_papertrail_follow:
      - /var/log/nginx/http-*error.log

    php_fpm_papertrail_follow:
      - /var/log/php-fpm/www-error.log

    ## Newrelic ##
    newrelic_enabled: True
    newrelic_infra_enabled: True
    # newrelic_license_key defined in prod_vars.yml
    newrelic_appname: "{{ project_name }}"


