---

# Note this file must be encrypted with ansible-vault!


drupal_db_password: "password_to_access_drupal_db1"
varnish_control_key: something-random-secret

external_smtp_sasl_password_maps: 'whateversecretstheexternalsmtpservicerequires'

