project:
  name: ansibleref
ansible:
  remote: https://github.com/wunderkraut/WunderMachina.git
  branch: master
  revision:
buildsh:
  enabled: true
  remote: https://raw.githubusercontent.com/wunderkraut/build.sh
  branch: develop
  revision:
wundertools:
  branch: master
externaldrupal:
  remote:
  branch:

