---
# Example site.yml

# The default environment is our local development environment.
# Note that the the default site is used as a base for all sites, so whatever you define here are inherited to
# other site definitions.
default:

  aliases: local

  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - files: web/sites/default/files
    - conf/settings.local.php: web/sites/default/settings.local.php

  local_commands:
    new:
      - shell: echo "Use the 'create' command to create a new project and the 'reset' command to join an existing one."

    create:
      - verify: "Type yes to verify you want to create a new installation: "
      - make
      - drush: site-install standard
      - drush: cex
      - shell: echo "New installation is complete and configuration has been exported. Please commit it."
      - cleanup

    reset:
      - verify: "Type yes to verify you want to reset your local environment: "
      - make
      - drush: site-install config_installer
      - cleanup

    # Basic site update functionality
    update:
      - backup
      - make
      - update
      - drush: cim
      - drush: entity-updates
      - cleanup

# Test environment:
test:

  aliases: stage

  # Test environment only symlinks files
  link:
    - files: web/sites/default/files


  # You can use copy to put some custom files in place if needed
  copy:
    #- conf/_ping.php: web/_ping.php
  # We can provide local commands or override global ones.
  local_commands:
    create:
      - shell: echo "Creating a new installation should only be done in local environments."

    reset:
      - verify: "Type yes to verify you want to reset your local environment: "
      - backup
      - make
      - drush: site-install config_installer
      - cleanup

    # Basic site update functionality
    update:
      - shell: chmod -R a+w web
      - backup
      - make
      - update
      - drush: cim
      - drush: entity-updates
      - cleanup
      - shell: chmod -R a-w web

# Production environment:
production:

  aliases: prod

  # Directory used to build the site
  temporary: _build

  # The final produced Drupal installation
  final: current

  # The Subpath of "final" and "temporary" where drupal resides.
  drupal_subpath: web

  build_in_place: False

  # Prod environment only symlinks files
  link:
    - files: web/sites/default/files

  copy:
    - web: web/
    - composer.json: composer.json
    - sync: sync

  local_commands:
    create:
      - shell: echo "Creating a new installation should only be done in local environments."

    reset:
      - verify: "Type yes to verify you want to reset your local environment: "
      - backup
      - make
      - drush: site-install config_installer
      - cleanup


    # Basic site update functionality
    update:
      - shell: chmod -R a+w current
      - backup
      - make
      - finalize
      - update
      - drush: cim
      - drush: entity-updates
      - cleanup
      - shell: chmod -R a-w current

    hotfix:
      - link
      - shell: chmod -R a+w current
      - shell: rsync -a _build/ current
      - shell: rm -r _build
      - shell: chmod -R a-w current
      - update


