---
# Example site.yml

# The default environment is our local development environment.
# Note that the the default site is used as a base for all sites, so whatever you define here are inherited to
# other site definitions.
default:

  # An alias or aliases for the site, this could also be:
  # aliases:
  #   - vagrant
  #   - mylocalbox
  aliases: vagrant
  aliases: local

  # Omit makefile to leave out drush
  # makefile: conf/site.make
  type: composer

  # Specify Drupal version
  drupal_version: d8

  # The final produced Drupal installation
  final: .

  # The Subpath of "final" and "temporary" where drupal resides.
  drupal_subpath: /web
  # Directory which will house all the previous builds
  previous: builds

  # Installation profile to use
  profile: config_installer

  # Site name given at installation phase
  site: Wundersite

  build_in_place: True

  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - files: web/sites/default/files
    - conf/settings.local.php: web/sites/default/settings.local.php

  local_commands:
    new:
      - verify: "Type yes to verify you want to build a new installation: "
      - make
      - backup
      - install
      - drush: cim
      - drush: cr
      - cleanup


    # Basic site update functionality
    update:
      - make
      - backup
      - update
      - drush: cim
      - drush: cr
      - drush: entity-updates
      - cleanup





# Test environment:
test:

  aliases: stage

  # Test environment only symlinks files
  link:
    - files: web/sites/default/files


  # You can use copy to put some custom files in place if needed
  copy:
    #- conf/_ping.php: web/_ping.php
  # We can provide local commands or override global ones.
  local_commands:
    new:
      - verify: "Type yes to verify you want to build a new installation: "
      - shell: chmod -R a+w web
      - make
      - backup
      - install
      - drush: cim
      - drush: cr
      - cleanup
      - shell: chmod -R a-w web


    # Basic site update functionality
    update:
      - shell: chmod -R a+w web
      - make
      - backup
      - update
      - drush: cim
      - drush: cr
      - drush: entity-updates
      - cleanup
      - shell: chmod -R a-w web


    # Running command ./build.sh hello test will print Hello world!
    hello:
      - shell: echo "Hello world!"

# Production environment:
production:

  aliases: prod

  # Directory used to build the site
  temporary: _build

  make_cache: .make_cache

  # Specify Drupal version
  drupal_version: d8

  # The final produced Drupal installation
  final: current

  # The Subpath of "final" and "temporary" where drupal resides.
  drupal_subpath: web

  build_in_place: False

  # Prod environment only symlinks files
  link:
    - files: web/sites/default/files

  copy:
    - web: web/
    - composer.json: composer.json
    - sync: sync

  local_commands:
    new:
      - verify: "Type yes to verify you want to build a new installation: "
      - shell: chmod -R a+w current
      - make
      - backup
      - purge
      - finalize
      - install
      - drush: cim
      - drush: cr
      - cleanup
      - shell: chmod -R a-w current


    # Basic site update functionality
    update:
      - shell: chmod -R a+w current
      - make
      - backup
      - finalize
      - update
      - drush: cim
      - drush: entity-updates
      - drush: cr
      - cleanup
      - shell: chmod -R a-w current

    hotfix:
      - link
      - shell: chmod -R a+w current
      - shell: rsync -a _build/ current
      - shell: rm -r _build
      - shell: chmod -R a-w current
      - update


