---
# Example site.yml

# The default environment is our local development environment.
# Note that the the default site is used as a base for all sites, so whatever you define here are inherited to
# other site definitions.
default:

  # An alias or aliases for the site, this could also be:
  # aliases:
  #   - vagrant
  #   - mylocalbox
  aliases: vagrant
  aliases: local

  # Omit makefile to leave out drush
  # makefile: conf/site.make
  type: composer

  # Directory used to build the site
  temporary: _build

  make_cache: .make_cache

  # Specify Drupal version
  drupal_version: d8

  # The final produced Drupal installation
  final: current

  # The Subpath of "final" and "temporary" where drupal resides.
  drupal_subpath: /web
  # Directory which will house all the previous builds
  previous: builds

  # Installation profile to use
  profile: config_installer

  # Site name given at installation phase
  site: Wundersite

  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - conf/composer.json: composer.json
    - conf/composer.lock: composer.lock
    - files: web/sites/default/files
    - code/modules/custom: web/modules/custom
    - code/themes/custom: web/themes/custom
    - sync: sync

  copy:
    - conf/services.yml: web/sites/default/services.yml
    - conf/settings.php: web/sites/default/settings.php
    - conf/settings.local.php: web/sites/default/settings.local.php
    - conf/_ping.php: web/_ping.php
# Test environment:
test:

  aliases: stage

  # Test environment only symlinks files
  link:
    - files: web/sites/default/files

  # Other files are copied, again note the settings.php, in our test enviroment we want to use another settings file.
  link:
    - files: sites/default/files

  copy:
    - code/modules: web/modules
    - code/themes: web/themes
    - conf/composer.json: composer.json
    - conf/composer.lock: composer.lock
    - sync: sync
    - conf/settings.php: web/sites/default/settings.php
    - conf/stage.settings.php: web/sites/default/settings.local.php
    - conf/services.yml: web/sites/default/services.yml
    - conf/_ping.php: web/_ping.php
  # We can provide local commands or override global ones.
  local_commands:

    # Running command ./build.sh hello test will print Hello world!
    hello:
      - shell: echo "Hello world!"

# Production environment:
production:

  aliases: prod

  # Prod environment only symlinks files
  link:
    - files: web/sites/default/files

  # Other files are copied, note settings.php
  copy:
    - code/modules: web/modules
    - code/themes: web/themes
    - conf/composer.json: composer.json
    - conf/composer.lock: composer.lock
    - sync: sync
    - conf/settings.php: web/sites/default/settings.php
    - conf/prod.settings.php: web/sites/default/settings.local.php
    - conf/services.yml: web/sites/default/services.yml
    - conf/_ping.php: web/_ping.php
