---
# Example site.yml

# The default environment is our local development environment.
# Note that the the default site is used as a base for all sites, so whatever you define here are inherited to
# other site definitions.
default:

  aliases: local

  drupal_version: d8

  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - files: web/sites/default/files
    - conf/settings.local.php: web/sites/default/settings.local.php

  local_commands:
    new:
      - shell: echo "Use the 'create' command to create a new project and the 'reset' command to join an existing one."

    create:
      - verify: "Type yes to verify you want to create a new installation: "
      - make
      - drush: site-install standard
      - drush: cex
      - shell: echo "New installation is complete and configuration has been exported. Please commit it."
      - cleanup

    reset:
      - verify: "Type yes to verify you want to reset your local environment: "
      - make
      - drush: site-install config_installer
      - cleanup

    # Basic site update functionality
    update:
      - backup:
         ignore:
          - builds
      - make
      - update
      - drush: cim -y
      - drush: entity-updates -y
      - cleanup

# Test environment:
test:

  aliases: stage

  # Test environment only symlinks files
  link:
    - files: web/sites/default/files


  # You can use copy to put some custom files in place if needed
    #- conf/_ping.php: web/_ping.php
  # We can provide local commands or override global ones.
  local_commands:
    create:
      - shell: echo "Creating a new installation should only be done in local environments."

    reset:
      - verify: "Type yes to verify you want to reset your local environment: "
      - backup:
         ignore:
          - builds
      - make
      - drush: site-install config_installer
      - cleanup

    # Basic site update functionality
    update:
      - shell: chmod -R a+w web
      - backup:
         ignore:
          - builds
      - make
      - update
      - drush: cim -y
      - drush: entity-updates -y
      - cleanup
      - shell: chmod -R a-w web
      - shell: sudo systemctl restart nginx php-fpm varnish

# Production environment:
production:

  aliases: prod

  # Prod environment only symlinks files
  link:
    - files: web/sites/default/files

  local_commands:
    create:
      - shell: echo "Creating a new installation should only be done in local environments."

    reset:
      - verify: "Type yes to verify you want to reset your local environment: "
      - backup:
         ignore:
          - builds
      - make
      - drush: site-install config_installer
      - cleanup


    # Basic site update functionality
    update:
      - shell: chmod -R a+w current
      - backup:
         ignore:
          - builds
      - make
      - update
      - drush: cim -y
      - drush: entity-updates -y
      - cleanup
      - shell: chmod -R a-w current
      - shell: sudo systemctl restart nginx php-fpm varnish

